spring:
  cloud:
    config:
      name: ${spring.application.name}
      enabled: true
      discovery:
        service-id: config-server
        enabled: true

#eureka:
#  client:
#    serviceUrl.defaultZone: http://localhost:8761/eureka/
#    region: default
#    registryFetchIntervalSeconds: 5
